# Generated by Django 4.1.7 on 2023-04-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
